name: Run Football Data Pipeline

on:
  schedule:
    - cron: '0 0 * * *'  # Every day at 00:00 UTC
  workflow_dispatch:     # Optional: allows you to also run manually


jobs:
  run-scripts:
    runs-on: ubuntu-latest

    permissions:          # <-- required to push commits
      contents: write

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run data update scripts in sequence
      run: |
        python "Update Dataset.py"
        python "Fixture Scrape.py"
        python "StandardiseFixtures.py"
        python "Testing.py"

    - name: Commit and push updated CSVs + other files
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        
        # Stage CSV files inside football_csvs folder
        git add football_csvs/*.csv dataset.csv fixtures.csv football-predictor-ui/last_updated.txt football-predictor-ui/results.csv
        
        # Commit only if there are changes
        git diff --cached --quiet || git commit -m "Update football CSVs [skip ci]"
        
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Deploy website to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./football-predictor-ui
        publish_branch: gh-pages
